### ISSUE TITLE
Can't use in dedicated server 

### ISSUE THREAD

**Issue by losslauralin** [Nova-Committee/PriorityTarget#1]
Mod Version:PriorityTarget-Forge-1.18.2-2.0.0.jar
Log:
[net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /127.0.0.1:34476
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at committee.nova.prioritytarget.PriorityTarget.onPlayerTick(PriorityTarget.java:79) ~[PriorityTarget-Forge-1.18.2-2.0.0.jar%23216!/:1.18.2-2.0.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:879) ~[forge-1.18.2-40.2.1-universal.jar%23300!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:279) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?]
	... 9 more

**Comment by VulpesStella** [comment]
CurseForge 上发了。Issue 我先关了，有问题的话记得重新打开。
Released 2.0.1 on CurseForge. If the problem still occurs, reopen the issue :)

**Comment by wumengzhixing** [comment]
我的朋友，我在新版本也发现了这个问题
forge：40.2.0
mod版本：PriorityTarget-Forge-1.18.2-2.0.1
crash：
[进不去服务器.txt](https://github.com/Nova-Committee/PriorityTarget/files/11124221/default.txt)

**Comment by VulpesStella** [comment]
好了，2.0.2 已上传。（这次实测没问题了）

**Comment by wumengzhixing** [comment]
> 好了，2.0.2 已上传。（这次实测没问题了）

抱歉，我在测试后还是存在这个问题。这是错误报告：
[错误.txt](https://github.com/Nova-Committee/PriorityTarget/files/11128389/default.txt)
如果没装这个模组，服务器是可以进的，但是装了就会出现这个错误

**Comment by VulpesStella** [comment]
> > 好了，2.0.2 已上传。（这次实测没问题了）
> 
> 抱歉，我在测试后还是存在这个问题。这是错误报告： [错误.txt](https://github.com/Nova-Committee/PriorityTarget/files/11128389/default.txt) 如果没装这个模组，服务器是可以进的，但是装了就会出现这个错误

确定两边都更新了吗

**Comment by wumengzhixing** [comment]
> > > 好了，2.0.2 已上传。（这次实测没问题了）
> > 
> > 
> > 抱歉，我在测试后还是存在这个问题。这是错误报告： [错误.txt](https://github.com/Nova-Committee/PriorityTarget/files/11128389/default.txt) 如果没装这个模组，服务器是可以进的，但是装了就会出现这个错误
> 
> 确定两边都更新了吗

是的
![image](https://user-images.githubusercontent.com/88496786/229265621-998c590c-7065-4aea-ad5e-fffd987192f3.png)

**Comment by VulpesStella** [comment]
换模组后服务器重启过了吗

**Comment by wumengzhixing** [comment]
> 换模组后服务器重启过了吗

当然...

**Comment by VulpesStella** [comment]
多少有点迷惑了

**Comment by wumengzhixing** [comment]
> 多少有点迷惑了

我也不太懂为什么会这样或者我发给你我的服务器端你试试？

**Comment by VulpesStella** [comment]
> > 多少有点迷惑了
> 
> 我也不太懂为什么会这样或者我发给你我的服务器端你试试？

行

**Comment by wumengzhixing** [comment]
> > > 多少有点迷惑了
> > 
> > 
> > 我也不太懂为什么会这样或者我发给你我的服务器端你试试？
> 
> 行

奶牛快传: https://cowtransfer.com/s/2af4286a83c54a
